### ISSUE TITLE
Purchasing the PRO License 

### ISSUE THREAD

**Issue by ghost** [Simple-Press/simple-press#144]
Is the Project - Simple Press still alive :( as here its written its up for adoption https://wptavern.com/simplepress-forum-plugin-is-up-for-adoption : https://snipboard.io/6qLHXA.jpg

Is it safe to buy the plugin's add ons from its site if its in live status : https://simple-press.com/pricing/ - Once i buy where do I expect the tech support from because the website's support@simple-press.com email ID doesn't return any response.

**Comment by nigobo** [comment]
Hi!

Thanks for posting. The project and the plugin is very much alive!

We are a new excited team behind Simple:Press since a few months back. Our current focus is to give Simple:Press the love it deserves and needs to get everything up to date. Official PHP8 support, fixing bugs, a new modern theme and many other things are in the works.

It's very safe to purchase, we are commited to this plugin and will continue developing it.

And please feel free e–mail us either using `contact@simple-press.com` or `support@simple-press.com`. Have you tried emailing us? We answer every email we get.

Best regards,
Joakim @ Simple:Press

**Comment by ghost** [comment]
Thanks appreciate your reply.
